name: rank_hub
description: "A Otoge Ranking explorer app"
version: 1.0.1+2
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: #^4.7.2
    git:
      url: https://github.com/luis901101/getx_fork.git
      ref: old-4.7.0

  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  cached_network_image: ^3.4.1
  data_table_2: ^2.5.15
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.6
  convert: ^3.1.1
  screenshot: ^3.0.0
  permission_handler: ^11.3.1
  image: ^4.3.0
  http: ^1.2.2
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  share_plus: ^10.1.3
  pointycastle: ^3.6.2
  archive: ^4.0.7
  live_activities: 
    git:
      url: https://github.com/qianmo2233/flutter_live_activities.git
  mobile_scanner: ^7.1.3
  techno_kitchen_dart: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0
  build_runner: any
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - icon-1024.png
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon-1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon-1024.png"
  remove_alpha_ios: true
