name: rank_hub
description: "A Otoge Ranking explorer app"
version: 1.0.8
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
    git:
      url: https://github.com/luis901101/getx_fork.git
      ref: old-4.7.0

  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  cached_network_image: ^3.4.1
  data_table_2: ^2.5.15
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.6
  convert: ^3.1.1
  screenshot: ^3.0.0
  permission_handler: ^12.0.1
  image: ^4.3.0
  http: ^1.2.2
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  share_plus: ^10.1.3
  pointycastle: ^3.6.2
  archive: ^4.0.7
  live_activities: ^2.4.5
  mobile_scanner: ^7.1.3
  techno_kitchen_dart: "^1.1.2"
  qr_flutter: ^4.1.0
  device_info_plus: ^11.2.0
  jwt_decoder: ^2.0.1
  pinput: ^5.0.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^17.0.1
  amap_map: ^1.0.15
  carousel_slider: ^5.0.0
  soft_edge_blur: ^0.1.3
  gradient_blur: ^1.0.2+1
  geolocator: ^13.0.2
  map_launcher: ^3.5.0
  intl: ^0.20.2
  collection: ^1.19.1
  photo_view: ^0.15.0
  audioplayers: ^6.5.1
  marquee: ^2.3.0
  split_button_m3e: ^0.2.1
  file_picker: ^10.3.8

  phasetida_flutter:
    git:
      url: https://github.com/phasetida/phasetida_flutter.git
      ref: 0.3.0
  flutter_fullscreen: ^1.2.0
  simai_flutter: ^0.2.3
  fast_gbk: ^1.0.0
  brotli: ^0.6.0
  slide_countdown: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0
  build_runner: any
  flutter_launcher_icons: ^0.14.4
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - icon.png
    - assets/images/
    - assets/data/
    - assets/osu/
    - shorebird.yaml

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon.png"
  remove_alpha_ios: true
