name: rank_hub
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.10.0

dependencies:
  adaptive_action_sheet: ^2.0.3
  admonitions: ^1.1.0
  animated_digit: ^3.2.3
  app_settings: ^5.1.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  #camera: ^0.11.0+2
  calendar_date_picker2: ^1.1.8
  chart_sparkline: ^1.1.1
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.16
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  #fl_mlkit_text_recognize: ^3.2.0
  easy_image_viewer: ^1.5.1
  fl_heatmap: ^0.4.5
  flutter:
    sdk: flutter
  flutter_date_range_picker: ^0.1.1
  flutter_expandable_fab: ^2.3.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_inappwebview: ^6.1.5
  flutter_listfilter: ^0.0.10
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_staggered_animations: ^1.1.1
  github: ^9.24.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_multiisolate: ^1.3.2
  image: ^4.3.0
  image_gallery_saver_plus: ^3.0.5
  #image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  marquee: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  mvvm_plus: ^1.5.4
  #opencv_core: ^1.3.3
  native_flutter_proxy: ^0.1.15
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.4
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  #socks5_proxy: ^2.0.0
  statusbarz: ^1.0.14
  timeago: ^3.7.0
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
